Repository newamericafoundation/newamerica-cms, pull requests merged in 2020-01, with the labels that each got.

#1470 Add migration for fellowship year
  person/migrations/0013_auto_20200109_1646.py
Labels: 1 high, tbx

#1469 Fix/1468 save post under subprogram
  home/models.py
  programs/tests.py
Labels: tbx

#1472 For fellows program, hard code link to former fellows page
  newamericadotorg/assets/react/program-page/components/People.js
Labels: area/react, tbx

#1467 Update allowed_hosts
  newamericadotorg/settings/dev.py
  newamericadotorg/settings/production.py
Labels: area/python, tbx
